extension Strings {

    static let learn: [String: Pair] = [
        "learn.section.0": ("Primeiros passos", "First steps"),
        "learn.section.1": ("Método de principiante", "Beginner method"),
        "learn.section.2": ("Introdução ao CFOP", "Introduction to CFOP"),
        "learn.progress": ("%d de %d lições concluídas", "%d of %d lessons completed"),
        "learn.intro": ("Aprende a resolver o cubo camada a camada, ao teu ritmo.",
                        "Learn to solve the cube layer by layer, at your own pace."),
        "learn.streak": ("%d dias seguidos", "%d-day streak"),
        "learn.completed": ("Concluída", "Completed"),
        "lesson.tab.why": ("Porquê", "Why"),
        "lesson.tab.how": ("Como", "How"),
        "lesson.tab.practice": ("Praticar", "Practise"),
        "lesson.tab.quiz": ("Quiz", "Quiz"),
        "lesson.why": ("PORQUÊ", "WHY"),
        "lesson.how": ("COMO", "HOW"),
        "lesson.markDone": ("Marcar como concluída", "Mark as completed"),
        "lesson.watchSlowly": ("Ver em câmara lenta", "Watch in slow motion"),
        "anatomy.centers": ("Centros", "Centres"),
        "anatomy.edges": ("Arestas", "Edges"),
        "anatomy.corners": ("Cantos", "Corners"),
        "anatomy.centers.detail": ("6 centros, um por face. Nunca saem do sítio: são eles que dizem a cor de cada face.",
                                   "6 centres, one per face. They never move, so they tell you the colour of each face."),
        "anatomy.edges.detail": ("12 arestas, cada uma com 2 cores. Uma aresta é sempre aresta: nunca vira canto.",
                                 "12 edges, each with 2 colours. An edge is always an edge: it can never become a corner."),
        "anatomy.corners.detail": ("8 cantos, cada um com 3 cores. Resolver o cubo é pôr cada canto e cada aresta no seu lugar.",
                                   "8 corners, each with 3 colours. Solving the cube means putting every corner and edge in its place."),
        "practice.goal": ("OBJETIVO", "GOAL"),
        "practice.newCase": ("Novo caso", "New case"),
        "practice.suggested": ("Sugestão:", "Suggested:"),
        "practice.start": ("Roda o cubo para começar", "Turn the cube to begin"),
        "practice.correct": ("Boa! Esse era o movimento certo.", "Nice! That was the right move."),
        "practice.wrong": ("%@ não era o movimento sugerido. Podes continuar ou desfazer.",
                           "%@ wasn't the suggested move. Keep going or undo it."),
        "practice.done": ("Conseguiste! Lição concluída.", "You did it! Lesson completed."),
        "practice.goal.whiteCross": ("Faz a cruz branca em baixo, com cada aresta alinhada com o centro do lado.",
                                     "Build the white cross at the bottom, each edge matching its side centre."),
        "practice.goal.whiteCorners": ("Completa a primeira camada: os quatro cantos brancos no sítio.",
                                       "Finish the first layer: all four white corners in place."),
        "practice.goal.middleEdges": ("Coloca as quatro arestas da camada do meio.", "Place the four middle-layer edges."),
        "practice.goal.yellowCross": ("Faz aparecer uma cruz amarela em cima.", "Make a yellow cross appear on top."),
        "practice.goal.yellowFace": ("Deixa a face de cima toda amarela.", "Make the whole top face yellow."),
        "practice.goal.yellowCorners": ("Põe os cantos amarelos nos seus lugares.", "Put the yellow corners in their places."),
        "practice.goal.yellowEdges": ("Acaba o cubo trocando as arestas de cima.", "Finish the cube by cycling the top edges."),
        "practice.goal.f2l": ("Resolve as duas primeiras camadas, com a cruz já feita.", "Solve the first two layers; the cross is done."),
        "practice.goal.oll": ("Orienta a última camada: face de cima toda amarela.", "Orient the last layer: the whole top face yellow."),
        "practice.goal.pll": ("Permuta a última camada e resolve o cubo.", "Permute the last layer and solve the cube."),
        "practice.goal.anatomy": ("", ""),
        "practice.goal.notation": ("", ""),
        "quiz.intro": ("Vais ver um movimento no cubo. Escolhe a notação certa. Acerta 4 em 5 para concluir a lição.",
                       "You'll see a move on the cube. Pick the right notation. Get 4 out of 5 to complete the lesson."),
        "quiz.start": ("Começar o quiz", "Start the quiz"),
        "quiz.question": ("Que movimento foi este?", "Which move was this?"),
        "quiz.replay": ("Ver outra vez", "Watch again"),
        "quiz.score": ("%d de %d", "%d out of %d"),
        "quiz.passed": ("Já falas a língua do cubo!", "You speak cube now!"),
        "quiz.tryAgain": ("Quase! Revê as letras no separador Como e tenta outra vez.",
                          "Almost! Review the letters in the How tab and try again."),
        "quiz.again": ("Repetir", "Try again"),
    ]

    static let lessons: [String: Pair] = [
        "lesson.anatomy.title": ("Conhecer o cubo", "Meet the cube"),
        "lesson.anatomy.subtitle": ("Centros, arestas e cantos", "Centres, edges and corners"),
        "lesson.anatomy.why": ("Um cubo 3×3 parece ter 54 quadradinhos soltos, mas é feito de 26 peças. Quando percebes que as peças se movem inteiras, deixas de pensar em cores soltas e passas a pensar em peças: é esse o segredo de qualquer método.",
                               "A 3×3 cube looks like 54 loose squares, but it is built from 26 pieces. Once you see that pieces move as a whole, you stop thinking about loose colours and start thinking about pieces: that is the secret behind every method."),
        "lesson.anatomy.how": ("Toca em Centros, Arestas e Cantos para os destacar. Os centros estão presos ao eixo interior, por isso ficam sempre no mesmo sítio uns em relação aos outros: o branco é oposto ao amarelo, o verde ao azul e o vermelho ao laranja.",
                               "Tap Centres, Edges and Corners to highlight them. Centres are fixed to the inner core, so they always keep the same place relative to each other: white is opposite yellow, green opposite blue and red opposite orange."),
        "lesson.notation.title": ("Notação", "Notation"),
        "lesson.notation.subtitle": ("A língua dos algoritmos", "The language of algorithms"),
        "lesson.notation.why": ("Para seguir um algoritmo tens de saber ler movimentos. Cada letra é uma face: R direita, L esquerda, U cima, D baixo, F frente, B trás. Com meia dúzia de letras consegues escrever qualquer solução.",
                                "To follow an algorithm you need to read moves. Each letter is a face: R right, L left, U up, D down, F front, B back. With a handful of letters you can write down any solution."),
        "lesson.notation.how": ("Uma letra sozinha roda essa face 90° no sentido dos ponteiros do relógio, olhando para ela. Com apóstrofo (R') roda ao contrário. Com 2 (R2) dá meia volta. M, E e S rodam as camadas do meio; x, y e z rodam o cubo inteiro. Toca numa letra para a veres no cubo.",
                                "A letter on its own turns that face 90° clockwise, as if you were looking at it. With a prime (R') it turns the other way. With a 2 (R2) it turns half way round. M, E and S turn the middle slices; x, y and z turn the whole cube. Tap a letter to see it on the cube."),
        "lesson.whiteCross.title": ("Cruz branca", "White cross"),
        "lesson.whiteCross.subtitle": ("A base de tudo", "The foundation"),
        "lesson.whiteCross.why": ("Resolvemos o cubo por camadas, de baixo para cima. A cruz branca prende as quatro arestas da primeira camada e já deixa as faces laterais alinhadas com os seus centros.",
                                  "We solve the cube in layers, from bottom to top. The white cross locks in the four edges of the first layer and lines the side faces up with their centres."),
        "lesson.whiteCross.how": ("Segura o cubo com o centro branco em baixo. Procura uma aresta branca, leva-a para cima da sua cor e depois baixa-a com uma meia volta dessa face. Não há algoritmo para decorar: é intuição, e melhora muito com a prática.",
                                  "Hold the cube with the white centre at the bottom. Find a white edge, bring it above its colour and then drop it with a half turn of that face. There is no algorithm to memorise: it's intuition, and practice makes it much better."),
        "lesson.whiteCross.tip": ("Olha sempre para a cor lateral da aresta, não só para o branco: tem de bater com o centro.",
                                  "Always check the side colour of the edge, not just the white: it must match the centre."),
        "lesson.whiteCorners.title": ("Cantos brancos", "White corners"),
        "lesson.whiteCorners.subtitle": ("Fechar a primeira camada", "Finish the first layer"),
        "lesson.whiteCorners.why": ("Com a cruz feita, faltam os quatro cantos para completar a primeira camada. Usamos um movimento curto que traz o canto para baixo sem estragar a cruz.",
                                    "With the cross done, four corners are missing from the first layer. We use a short move that brings the corner down without breaking the cross."),
        "lesson.whiteCorners.how": ("Coloca o canto em cima, por cima do sítio onde tem de ir (à frente e à direita). Vê para onde está virado o branco: para a direita faz R U R', para a frente faz F' U' F, para cima faz R U2 R' U' R U R'. Se te baralhares, há um truque que funciona sempre: repete R U R' U' até o canto ficar certo. Se o canto estiver em baixo no sítio errado, faz R U R' uma vez para o tirar de lá.",
                                    "Put the corner on top, above the spot where it belongs (front right). Check where the white faces: right, do R U R'; front, do F' U' F; up, do R U2 R' U' R U R'. If you get lost, one trick always works: repeat R U R' U' until the corner is right. If the corner is at the bottom in the wrong place, do R U R' once to pop it out."),
        "lesson.middleEdges.title": ("Camada do meio", "Middle layer"),
        "lesson.middleEdges.subtitle": ("Duas camadas feitas", "Two layers done"),
        "lesson.middleEdges.why": ("As quatro arestas sem amarelo pertencem à camada do meio. Metê-las no sítio sem mexer na primeira camada exige um algoritmo que tira o canto do caminho e o repõe logo a seguir.",
                                   "The four edges without yellow belong in the middle layer. Inserting them without disturbing the first layer takes an algorithm that moves a corner out of the way and puts it straight back."),
        "lesson.middleEdges.how": ("Procura em cima uma aresta sem amarelo. Roda U até a cor da frente dela bater com o centro da frente. Se a cor de cima pertence ao centro da direita, usa o algoritmo para a direita; se pertence ao da esquerda, usa o da esquerda.",
                                   "Find an edge on top without yellow. Turn U until its front colour matches the front centre. If its top colour belongs to the right centre, use the right-hand algorithm; if it belongs to the left, use the left-hand one."),
        "lesson.yellowCross.title": ("Cruz amarela", "Yellow cross"),
        "lesson.yellowCross.subtitle": ("A última camada começa", "The last layer begins"),
        "lesson.yellowCross.why": ("Agora a face amarela está em cima. Primeiro viramos as arestas para mostrarem o amarelo: ainda não importa onde estão, só para onde estão viradas.",
                                   "The yellow face is now on top. First we flip the edges so they show yellow: it doesn't matter yet where they are, only which way they face."),
        "lesson.yellowCross.how": ("Olha para as arestas de cima. Vês um ponto, um L ou uma linha. Com o L à esquerda e atrás, ou com a linha na horizontal, faz F R U R' U' F'. Repete até aparecer a cruz.",
                                   "Look at the top edges. You'll see a dot, an L or a line. With the L at the back left, or the line horizontal, do F R U R' U' F'. Repeat until the cross appears."),
        "lesson.yellowFace.title": ("Face amarela", "Yellow face"),
        "lesson.yellowFace.subtitle": ("Orientar os cantos", "Orient the corners"),
        "lesson.yellowFace.why": ("Com a cruz amarela feita, os cantos ainda podem estar virados. O Sune roda três cantos de uma vez e mantém tudo o que já está resolvido.",
                                  "With the yellow cross done, the corners may still be twisted. The Sune turns three corners at once and keeps everything already solved."),
        "lesson.yellowFace.how": ("Se houver só um canto amarelo em cima, põe-no à frente e à esquerda e faz o Sune. Caso contrário, roda U até haver amarelo virado para a esquerda no canto da frente, faz o Sune e repete até a face estar toda amarela.",
                                  "If exactly one corner shows yellow on top, put it at the front left and do the Sune. Otherwise turn U until the front-left corner has yellow facing left, do the Sune and repeat until the whole face is yellow."),
        "lesson.yellowCorners.title": ("Cantos amarelos", "Yellow corners"),
        "lesson.yellowCorners.subtitle": ("Cada canto no seu lugar", "Every corner in place"),
        "lesson.yellowCorners.why": ("A face de cima está amarela, mas os cantos podem estar trocados. O algoritmo A troca três cantos entre si sem os virar.",
                                     "The top face is yellow, but the corners may be in the wrong places. The A algorithm cycles three corners without twisting them."),
        "lesson.yellowCorners.how": ("Procura dois cantos que já estejam certos um em relação ao outro (os faróis) e usa o algoritmo A para rodar os outros três. Se rodarem no sentido errado, usa a outra versão do A. Sem faróis, faz um A de qualquer lado e procura outra vez. A dica mostra-te sempre o ângulo certo.",
                                     "Find two corners that are already right relative to each other (the headlights) and use the A algorithm to cycle the other three. If they go the wrong way, use the other A. With no headlights, do an A from any side and look again. The hint always shows the right angle."),
        "lesson.yellowEdges.title": ("Arestas amarelas", "Yellow edges"),
        "lesson.yellowEdges.subtitle": ("O cubo resolvido", "The solved cube"),
        "lesson.yellowEdges.why": ("Falta só trocar as arestas de cima. O algoritmo U roda três arestas e deixa os cantos intactos.",
                                   "All that's left is cycling the top edges. The U algorithm rotates three edges and leaves the corners alone."),
        "lesson.yellowEdges.how": ("Se uma face lateral já estiver completa, põe-na atrás e faz o U. Vê se as arestas rodaram no sentido certo; se não, faz o outro U. Sem nenhuma face completa, faz um deles uma vez e recomeça.",
                                   "If one side is already complete, put it at the back and do a U algorithm. Check whether the edges went the right way; if not, use the other one. With no complete side, do either one once and start again."),
        "lesson.yellowEdges.tip": ("Parabéns: com estas sete etapas consegues resolver qualquer cubo baralhado.",
                                   "Congratulations: with these seven stages you can solve any scrambled cube."),
        "lesson.f2l.title": ("F2L intuitivo", "Intuitive F2L"),
        "lesson.f2l.subtitle": ("Canto e aresta juntos", "Corner and edge together"),
        "lesson.f2l.why": ("No CFOP, depois da cruz, resolves cada canto branco com a aresta do meio que lhe corresponde, ao mesmo tempo. Poupas metade dos movimentos das duas primeiras camadas.",
                           "In CFOP, after the cross, you solve each white corner together with its matching middle edge. It saves about half the moves of the first two layers."),
        "lesson.f2l.how": ("Junta o canto e a aresta na camada de cima, formando um par, e insere o par de uma vez com R U R' ou movimentos parecidos. Começa devagar: o objetivo é perceber porque é que o par se forma, não decorar casos.",
                           "Pair the corner and the edge up in the top layer, then insert the pair in one go with R U R' or similar moves. Start slowly: the aim is to understand why the pair forms, not to memorise cases."),
        "lesson.oll.title": ("OLL em 2 passos", "2-look OLL"),
        "lesson.oll.subtitle": ("Face amarela mais depressa", "A faster yellow face"),
        "lesson.oll.why": ("O OLL orienta toda a última camada. Em dois passos precisas de poucos algoritmos: um para as arestas (cruz) e um para os cantos.",
                           "OLL orients the whole last layer. In two looks you only need a few algorithms: one for the edges (cross) and one for the corners."),
        "lesson.oll.how": ("Primeiro faz a cruz amarela com F R U R' U' F' ou f R U R' U' f'. Depois reconhece o caso dos cantos (Sune, Anti-Sune, H, Pi, Faróis, T ou Laço) e aplica o algoritmo certo.",
                           "First make the yellow cross with F R U R' U' F' or f R U R' U' f'. Then recognise the corner case (Sune, Anti-Sune, H, Pi, Headlights, T or Bowtie) and apply the matching algorithm."),
        "lesson.pll.title": ("PLL em 2 passos", "2-look PLL"),
        "lesson.pll.subtitle": ("Acabar com estilo", "Finish in style"),
        "lesson.pll.why": ("O PLL põe as peças da última camada no sítio sem as virar. Em dois passos: primeiro os cantos, depois as arestas.",
                           "PLL moves the last-layer pieces into place without twisting them. In two looks: corners first, then edges."),
        "lesson.pll.how": ("Com faróis, faz a permutação T com os faróis à esquerda. Sem faróis, faz a permutação Y. Depois acaba as arestas com Ua, Ub, H ou Z.",
                           "With headlights, do the T permutation with the headlights on the left. Without them, do the Y permutation. Then finish the edges with Ua, Ub, H or Z."),
    ]

    static let lessonSteps: [String: Pair] = [
        "algorithm.sexy": ("Movimento básico", "Sexy move"),
        "algorithm.cornerRight": ("Branco à direita", "White facing right"),
        "algorithm.cornerFront": ("Branco à frente", "White facing front"),
        "algorithm.cornerUp": ("Branco para cima", "White facing up"),
        "algorithm.rightInsert": ("Aresta para a direita", "Right-hand edge"),
        "algorithm.leftInsert": ("Aresta para a esquerda", "Left-hand edge"),
        "algorithm.yellowCross": ("Cruz amarela", "Yellow cross"),
        "algorithm.sune": ("Sune", "Sune"),
        "algorithm.antiSune": ("Anti-Sune", "Anti-Sune"),
        "algorithm.aPermA": ("Permutação A (a)", "A permutation (a)"),
        "algorithm.aPermB": ("Permutação A (b)", "A permutation (b)"),
        "algorithm.uPermA": ("Permutação U (a)", "U permutation (a)"),
        "algorithm.uPermB": ("Permutação U (b)", "U permutation (b)"),
        "algorithm.ollLine": ("Linha", "Line"),
        "algorithm.ollAngle": ("L pequeno", "Small L"),
        "algorithm.ollH": ("H", "H"),
        "algorithm.ollPi": ("Pi", "Pi"),
        "algorithm.ollHeadlights": ("Faróis", "Headlights"),
        "algorithm.ollT": ("T", "T"),
        "algorithm.ollBowtie": ("Laço", "Bowtie"),
        "algorithm.pllT": ("Permutação T", "T permutation"),
        "algorithm.pllY": ("Permutação Y", "Y permutation"),
        "algorithm.pllH": ("Permutação H", "H permutation"),
        "algorithm.pllZ": ("Permutação Z", "Z permutation"),
    ]

    static let achievements: [String: Pair] = [
        "achievements.title": ("Conquistas", "Achievements"),
        "achievements.unlocked": ("CONQUISTA DESBLOQUEADA", "ACHIEVEMENT UNLOCKED"),
        "achievements.earned": ("Conquistada", "Earned"),
        "achievements.locked": ("Por conquistar", "Locked"),
        "achievement.firstCross.title": ("Primeira cruz", "First cross"),
        "achievement.firstCross.detail": ("Conclui a lição da cruz branca", "Finish the white cross lesson"),
        "achievement.firstSolve.title": ("Primeiro cubo", "First cube"),
        "achievement.firstSolve.detail": ("Resolve um cubo no modo Jogar", "Solve a cube in Play"),
        "achievement.underTwoMinutes.title": ("Menos de 2 minutos", "Under 2 minutes"),
        "achievement.underTwoMinutes.detail": ("Resolve o 3×3 em menos de 2 minutos", "Solve the 3×3 in under 2 minutes"),
        "achievement.underOneMinute.title": ("Menos de 1 minuto", "Under 1 minute"),
        "achievement.underOneMinute.detail": ("Resolve o 3×3 em menos de 1 minuto", "Solve the 3×3 in under a minute"),
        "achievement.weekStreak.title": ("7 dias seguidos", "7-day streak"),
        "achievement.weekStreak.detail": ("Joga ou aprende 7 dias seguidos", "Play or learn 7 days in a row"),
        "achievement.graduate.title": ("Diploma de principiante", "Beginner graduate"),
        "achievement.graduate.detail": ("Conclui todas as lições do método de principiante", "Finish every beginner-method lesson"),
        "achievement.dailyChallenge.title": ("Desafio aceite", "Challenge accepted"),
        "achievement.dailyChallenge.detail": ("Completa um desafio diário", "Complete a daily challenge"),
        "achievement.bigCube.title": ("Cubo grande", "Big cube"),
        "achievement.bigCube.detail": ("Resolve um 4×4", "Solve a 4×4"),
        "achievement.scanner.title": ("Do real para o ecrã", "Real to screen"),
        "achievement.scanner.detail": ("Lê um cubo verdadeiro com a câmara", "Scan a real cube with the camera"),
    ]
}
