extension Strings {

    static let home: [String: Pair] = [
        "mode.play": ("Jogar", "Play"),
        "mode.play.subtitle": ("Baralha e resolve contra o relógio", "Scramble and race the clock"),
        "mode.assist": ("Ajudar", "Assist"),
        "mode.assist.subtitle": ("Dicas, próximo movimento e solução completa", "Hints, next move and the full solution"),
        "mode.learn": ("Aprender", "Learn"),
        "mode.learn.subtitle": ("Do zero ao cubo resolvido, passo a passo", "From zero to a solved cube, step by step"),
        "home.lastTime": ("Último", "Last"),
        "home.bestTime": ("Melhor 3×3", "Best 3×3"),
        "home.lessons": ("Lições", "Lessons"),
        "home.daily": ("Desafio diário", "Daily challenge"),
        "home.dailyNew": ("O mesmo baralhar para toda a gente, hoje", "The same scramble for everyone, today"),
        "home.dailyBest": ("O teu melhor tempo hoje: %@", "Your best time today: %@"),
        "home.scanner": ("Scanner", "Scanner"),
        "home.stats": ("Estatísticas", "Statistics"),
    ]

    static let settings: [String: Pair] = [
        "settings.title": ("Definições", "Settings"),
        "settings.language": ("Idioma", "Language"),
        "settings.appearance": ("Aparência", "Appearance"),
        "settings.appearance.system": ("Sistema", "System"),
        "settings.appearance.light": ("Claro", "Light"),
        "settings.appearance.dark": ("Escuro", "Dark"),
        "settings.cube": ("Cubo", "Cube"),
        "settings.animationSpeed": ("Velocidade das animações", "Animation speed"),
        "settings.speed.slow": ("Lenta", "Slow"),
        "settings.speed.normal": ("Normal", "Normal"),
        "settings.speed.fast": ("Rápida", "Fast"),
        "settings.highContrast": ("Cores de alto contraste", "High-contrast colours"),
        "settings.highContrast.detail": ("Paleta segura para daltonismo, com um símbolo em cada cor",
                                         "Colour-blind-safe palette with a symbol on every colour"),
        "settings.notationPanel": ("Painel de notação", "Notation panel"),
        "settings.notationPanel.detail": ("Mostrar os botões R, U, F… ao abrir o modo Jogar",
                                          "Show the R, U, F… buttons when Play opens"),
        "settings.play": ("Jogar", "Play"),
        "settings.inspection": ("Inspeção de 15 segundos", "15-second inspection"),
        "settings.inspection.detail": ("Tempo para estudar o cubo antes de o relógio arrancar",
                                       "Time to study the cube before the clock starts"),
        "settings.feedback": ("Som e vibração", "Sound and haptics"),
        "settings.sound": ("Som", "Sound"),
        "settings.haptics": ("Vibração", "Haptics"),
        "settings.data": ("Dados", "Data"),
        "settings.resetStats": ("Repor estatísticas", "Reset statistics"),
        "settings.resetStats.confirm": ("Apagar todos os tempos?", "Delete every time?"),
        "settings.resetStats.message": ("Os tempos e o histórico de soluções são apagados deste aparelho. O progresso das lições mantém-se.",
                                        "Times and solve history are deleted from this device. Lesson progress is kept."),
        "settings.resetStats.done": ("Estatísticas repostas", "Statistics reset"),
        "settings.sync": ("As definições e o progresso das lições sincronizam com o iCloud.",
                          "Settings and lesson progress sync with iCloud."),
        "settings.about": ("Sobre", "About"),
    ]

    static let play: [String: Pair] = [
        "play.scramble": ("Baralhar", "Scramble"),
        "play.newScramble": ("Novo baralhar", "New scramble"),
        "play.noScramble": ("Toca em Baralhar para começar.", "Tap Scramble to begin."),
        "play.pause": ("Pausa", "Pause"),
        "play.paused": ("Em pausa", "Paused"),
        "play.resume": ("Continuar", "Resume"),
        "play.togglePad": ("Mostrar ou ocultar a notação", "Show or hide notation"),
        "play.historyEmpty": ("Os teus movimentos aparecem aqui", "Your moves show up here"),
        "play.inspection": ("Inspeção", "Inspection"),
        "play.caption.idle": ("Pronto quando quiseres", "Ready when you are"),
        "play.caption.scrambling": ("A baralhar…", "Scrambling…"),
        "play.caption.waiting": ("O relógio arranca no primeiro movimento", "The clock starts on your first move"),
        "play.caption.solving": ("Força!", "Go!"),
        "play.caption.solved": ("Resolvido!", "Solved!"),
        "result.solved": ("Resolvido!", "Solved!"),
        "result.newBest": ("Novo recorde!", "New record!"),
        "result.previousBest": ("Recorde", "Record"),
        "result.difference": ("Diferença", "Difference"),
    ]

    static let assist: [String: Pair] = [
        "assist.method.optimal": ("Ótima", "Optimal"),
        "assist.method.beginner": ("Principiante", "Beginner"),
        "assist.whereAmI": ("Onde estou", "Where am I"),
        "assist.whereSummary": ("Faltam %d etapas do método de principiante.", "%d beginner-method stages to go."),
        "assist.whereSolved": ("O cubo está resolvido. Muito bem!", "The cube is solved. Well done!"),
        "assist.now": ("AGORA", "NOW"),
        "assist.hint": ("Dica", "Hint"),
        "assist.doIt": ("Faz por mim", "Do it for me"),
        "assist.solveAll": ("Resolver tudo", "Solve all"),
        "assist.next": ("Próximo:", "Next:"),
        "assist.historyEmpty": ("Resolve à tua maneira e pede ajuda quando precisares",
                                "Solve your way and ask for help whenever you need"),
        "assist.play": ("Reproduzir", "Play"),
        "assist.stepBack": ("Passo anterior", "Previous step"),
        "assist.stepForward": ("Passo seguinte", "Next step"),
        "assist.speed": ("Velocidade", "Speed"),
        "assist.speed.slow": ("Lenta", "Slow"),
        "assist.speed.normal": ("Normal", "Normal"),
        "assist.speed.fast": ("Rápida", "Fast"),
        "assist.stopPlayback": ("Parar a reprodução", "Stop playback"),
        "assist.scan": ("Ler o meu cubo com a câmara", "Scan my cube with the camera"),
        "assist.manual": ("Introduzir cores à mão", "Enter colours by hand"),
        "assist.resetCube": ("Repor o cubo", "Reset the cube"),
        "assist.cubeMenu": ("Opções do cubo", "Cube options"),
        "assist.invalidTitle": ("Este cubo não é possível", "This cube is impossible"),
        "assist.placePiece": ("Coloca a peça %@ no sítio certo", "Put the %@ piece in place"),
        "assist.usingAlgorithm": ("Com o algoritmo %@", "Using the %@ algorithm"),
        "validation.colorCount": ("Cada cor tem de aparecer exatamente 9 vezes.", "Each colour must appear exactly 9 times."),
        "validation.centers": ("Os seis centros têm de ter cores diferentes.", "The six centres must all be different colours."),
        "validation.corner": ("Há um canto com uma combinação de cores que não existe.", "A corner has a colour combination that does not exist."),
        "validation.edge": ("Há uma aresta com uma combinação de cores que não existe.", "An edge has a colour combination that does not exist."),
        "validation.twist": ("Há um canto rodado sobre si próprio. Num cubo real isso só acontece se for desmontado.",
                             "A corner is twisted in place. On a real cube that only happens if it was taken apart."),
        "validation.flip": ("Há uma aresta virada ao contrário. Num cubo real isso só acontece se for desmontado.",
                            "An edge is flipped. On a real cube that only happens if it was taken apart."),
        "validation.parity": ("Há duas peças trocadas entre si. Verifica as cores e tenta outra vez.",
                              "Two pieces are swapped. Check the colours and try again."),
    ]

    static let stages: [String: Pair] = [
        "stage.0.title": ("Segurar o cubo", "Hold the cube"),
        "stage.0.goal": ("Roda o cubo inteiro para o centro branco ficar em baixo.", "Turn the whole cube so the white centre is at the bottom."),
        "stage.1.title": ("Cruz branca", "White cross"),
        "stage.1.goal": ("As quatro arestas brancas em cruz, alinhadas com os centros.", "The four white edges in a cross, matching the centres."),
        "stage.2.title": ("Cantos brancos", "White corners"),
        "stage.2.goal": ("Completa a primeira camada com os quatro cantos brancos.", "Complete the first layer with the four white corners."),
        "stage.3.title": ("Camada do meio", "Middle layer"),
        "stage.3.goal": ("Coloca as quatro arestas sem amarelo na camada do meio.", "Place the four edges without yellow in the middle layer."),
        "stage.4.title": ("Cruz amarela", "Yellow cross"),
        "stage.4.goal": ("Forma uma cruz amarela na face de cima.", "Make a yellow cross on the top face."),
        "stage.5.title": ("Face amarela", "Yellow face"),
        "stage.5.goal": ("Vira os cantos até a face de cima ficar toda amarela.", "Twist the corners until the whole top face is yellow."),
        "stage.6.title": ("Cantos amarelos", "Yellow corners"),
        "stage.6.goal": ("Leva cada canto amarelo para o seu lugar.", "Move each yellow corner to its place."),
        "stage.7.title": ("Arestas amarelas", "Yellow edges"),
        "stage.7.goal": ("Troca as arestas de cima até o cubo ficar resolvido.", "Cycle the top edges until the cube is solved."),
        "stage.8.title": ("Resolvido", "Solved"),
        "stage.8.goal": ("Todas as faces estão completas.", "Every face is complete."),
    ]

    static let scanner: [String: Pair] = [
        "scanner.title": ("Ler o cubo", "Scan cube"),
        "scanner.instruction": ("Mostra a face com o centro %@, com o %@ virado para cima, dentro da grelha.",
                                "Show the face with the %@ centre, %@ facing up, inside the grid."),
        "scanner.capture": ("Capturar", "Capture"),
        "scanner.retake": ("Repetir a face anterior", "Retake the previous face"),
        "scanner.manual": ("À mão", "By hand"),
        "scanner.progress": ("%d de 6 faces lidas", "%d of 6 faces scanned"),
        "scanner.unavailable": ("Não há câmara disponível neste aparelho. Podes introduzir as cores à mão.",
                                "No camera is available on this device. You can enter the colours by hand."),
        "scanner.denied": ("O iRubikCube não tem acesso à câmara. Dá permissão nas Definições do iPhone ou introduz as cores à mão.",
                           "iRubikCube has no access to the camera. Allow it in the device Settings or enter the colours by hand."),
        "scanner.openSettings": ("Abrir Definições", "Open Settings"),
        "editor.title": ("Cores do cubo", "Cube colours"),
        "editor.help": ("Escolhe uma cor em baixo e toca nos autocolantes para os pintar. Os centros estão fixos.",
                        "Pick a colour below and tap stickers to paint them. The centres are fixed."),
        "editor.clear": ("Limpar", "Clear"),
        "editor.solved": ("Resolvido", "Solved"),
        "editor.solve": ("Resolver este cubo", "Solve this cube"),
        "editor.empty": ("Vazio", "Empty"),
        "editor.incomplete": ("Ainda há autocolantes por pintar.", "Some stickers are still empty."),
    ]

    static let stats: [String: Pair] = [
        "stats.title": ("Estatísticas", "Statistics"),
        "stats.best": ("Melhor", "Best"),
        "stats.mean": ("Média", "Mean"),
        "stats.solves": ("Resoluções", "Solves"),
        "stats.avgMoves": ("Mov. médios", "Avg. moves"),
        "stats.history": ("Evolução", "Progress"),
        "stats.chartEmpty": ("Resolve pelo menos dois cubos para veres o gráfico.", "Solve at least two cubes to see the chart."),
        "stats.chartLabel": ("Gráfico dos últimos tempos", "Chart of your latest times"),
        "stats.solutions": ("Soluções", "Solutions"),
        "stats.empty": ("Ainda não há tempos neste tamanho.", "No times for this size yet."),
        "stats.scramble": ("BARALHAR", "SCRAMBLE"),
        "stats.solution": ("SOLUÇÃO", "SOLUTION"),
    ]

    static let notation: [String: Pair] = [
        "notation.padHint": ("Toca para rodar", "Tap to turn"),
        "notation.primeToggle": ("Sentido contrário", "Anticlockwise"),
        "notation.doubleToggle": ("Meia volta", "Half turn"),
        "notation.speak.clockwise": ("sentido dos ponteiros do relógio", "clockwise"),
        "notation.speak.anticlockwise": ("sentido contrário", "anticlockwise"),
        "notation.speak.double": ("meia volta", "half turn"),
        "notation.name.R": ("Face direita", "Right face"),
        "notation.name.L": ("Face esquerda", "Left face"),
        "notation.name.U": ("Face de cima", "Up face"),
        "notation.name.D": ("Face de baixo", "Down face"),
        "notation.name.F": ("Face da frente", "Front face"),
        "notation.name.B": ("Face de trás", "Back face"),
        "notation.name.M": ("Camada do meio, como L", "Middle slice, like L"),
        "notation.name.E": ("Camada do equador, como D", "Equator slice, like D"),
        "notation.name.S": ("Camada de pé, como F", "Standing slice, like F"),
        "notation.name.x": ("Cubo inteiro, como R", "Whole cube, like R"),
        "notation.name.y": ("Cubo inteiro, como U", "Whole cube, like U"),
        "notation.name.z": ("Cubo inteiro, como F", "Whole cube, like F"),
        "notation.name.Rw": ("Duas camadas da direita", "Two right layers"),
        "notation.name.Uw": ("Duas camadas de cima", "Two top layers"),
        "notation.name.Fw": ("Duas camadas da frente", "Two front layers"),
        "face.U": ("Cima", "Up"),
        "face.D": ("Baixo", "Down"),
        "face.F": ("Frente", "Front"),
        "face.B": ("Trás", "Back"),
        "face.R": ("Direita", "Right"),
        "face.L": ("Esquerda", "Left"),
        "color.white": ("branco", "white"),
        "color.yellow": ("amarelo", "yellow"),
        "color.red": ("vermelho", "red"),
        "color.orange": ("laranja", "orange"),
        "color.blue": ("azul", "blue"),
        "color.green": ("verde", "green"),
    ]

    static let a11y: [String: Pair] = [
        "a11y.cube": ("Cubo 3D. Arrasta um autocolante para rodar uma camada, arrasta fora do cubo para o rodar todo.",
                      "3D cube. Drag a sticker to turn a layer, drag outside the cube to rotate it."),
        "a11y.cubeSolved": ("Cubo resolvido", "Solved cube"),
        "a11y.heroCube": ("Cubo a rodar", "Spinning cube"),
        "a11y.skipSplash": ("Saltar a apresentação", "Skip the intro"),
        "a11y.openWebsite": ("Abrir o site ividi.dev", "Open the ividi.dev website"),
        "a11y.openGitHub": ("Abrir o GitHub de David Arsénio Martins", "Open David Arsénio Martins on GitHub"),
    ]
}
